### ISSUE TITLE
when will u release the beta version 

### ISSUE THREAD

**Issue by witskeeper** [OpenSkywalking/SkyWalking-With-Es5x-Storage#5]
when will u release the beta version

**Comment by wu-sheng** [comment]
No alpha tag too. Need both od them.

**Comment by YoungHu** [comment]
No alpha tag too. Need both of them.

**Comment by YoungHu** [comment]
> No alpha tag too. Need both od them.

take few minutes to understand it, finally think 'od' maybe a wrong spell of 'of'

**Comment by witskeeper** [comment]
nice job,6.0.0-alpha released.
i will try
