### ISSUE TITLE
got error when build package

### ISSUE THREAD

**Issue by witskeeper** [OpenSkywalking/SkyWalking-With-Es5x-Storage#7]
>> mvn package

Could not resolve dependencies for project org.apache.skywalking:storage-elasticsearch5x-plugin:jar:6.0.0-alpha: Failure to find org.apache.skywalking:server-starter:jar:6.0.0-beta-SNAPSHOT in http://xxx.xxxx.com/repository/m
aven-public/ was cached in the local repository, resolution will not be reattempted until the update interval of nexus-maven-public has elapsed or updates are forced

**Comment by witskeeper** [comment]
where can i get org.apache.skywalking:server-starter:jar:6.0.0-beta-SNAPSHOT

**Comment by witskeeper** [comment]
can u publish a jar package？

**Comment by wu-sheng** [comment]
Beta is wrong dependency. Should depend on release version, no snapshot.

**Comment by witskeeper** [comment]
change  pom.xml
```
<core.version>6.0.0-beta-SNAPSHOT</core.version>
```
to
```
<core.version>6.0.0-beta</core.version>
```

and get error:

```
Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.0:compile (default-compile) on project storage-elasticsearch5x-plugin: Compilation failure: Compilation failure:
nt/ElasticSearchClient5x.java:[26,53] 找不到符号
[ERROR]   符号:   类 StringUtils
[ERROR]   位置: 程序包 org.apache.skywalking.oap.server.library.util

```

**Comment by witskeeper** [comment]
maybe missing  
```
org.apache.skywalking.oap.server.library.client.NameSpace;
```

**Comment by YoungHu** [comment]
take pr #6 to build
